ARG NIX_VERSION=2.34.8
FROM nixos/nix:${NIX_VERSION}
# FROM nixos/nix:2.34.8

ARG NIXPKGS_REV=e7a3ca8092b61ff85b6a45bf863ea2b2d6a661b3

RUN printf '%s\n' \
      'experimental-features = nix-command flakes' \
      'sandbox = false' \
      'build-users-group =' \
      >> /etc/nix/nix.conf

# RUN nix registry add --registry /etc/nix/registry.json \
#       nixpkgs github:NixOS/nixpkgs/${NIXPKGS_REV}

# Warm the store with the pinned nixpkgs source, and bake in your tools.
# RUN nix flake metadata nixpkgs >/dev/null

COPY flake.nix flake.lock /root/workspace/
WORKDIR /root/workspace
RUN nix develop --profile /root/devshell-profile -c true

RUN nix profile install \
      nixpkgs#fish nixpkgs#ncurses nixpkgs#starship nixpkgs#zoxide \
      nixpkgs#neovim nixpkgs#gh nixpkgs#ps


# put the linker where things expect it (not sure why its not their to begin with ¯\_(ツ)_/¯)
RUN chmod 755 /
RUN mkdir /lib64/
RUN cp /nix/store/ias8xacs1h3jy7xgwi2awvim61k2ji6c-glibc-2.42-67/lib/ld-linux-x86-64.so.2 /lib64/

ENV HOME=/root \
    TERM=xterm-256color \
    LANG=C.UTF-8 \
    TERMINFO_DIRS=/root/.nix-profile/share/terminfo \
    SHELL=/root/.nix-profile/bin/fish

CMD ["fish"]
